version: "3.3"
services:
    db:
        image: postgres
        container_name: tapir_db
        restart: always
        ports:
            - 8279:5432
        environment:
            POSTGRES_DB: tapir
            POSTGRES_USER: tapir
            POSTGRES_PASSWORD: qwerty
        volumes:
            - ./docker/db/data:/var/lib/postgresql/data
            - ./docker/db/dump:/docker-entrypoint-initdb.d
        networks:
            - tapir

    composer:
        image: composer
        command: dump-autoload -o
        volumes:
            - ./src:/app

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: tapir_php
        depends_on:
            - db
            - composer
        volumes:
            - ./src:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - tapir

    nginx:
        image: nginx
        restart: always
        container_name: tapir_nginx
        ports:
            - "8280:80" # при переопределении порта, требуется изминить его и в файле docker/swagger/swagger.yaml (порт в поле host)
        environment:
            - VIRTUAL_HOST=localhost
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/html
        depends_on:
            - php
            - db
        networks:
            - tapir

    swagger:
        image: redocly/redoc
        ports:
            - "8281:80"
        volumes:
            - ./docker/swagger/swagger.yaml:/usr/share/nginx/html/swagger.yaml
        environment:
            SPEC_URL: swagger.yaml
networks:
    tapir:
        ipam:
            config:
                - subnet: 192.168.111.0/24

